apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: darknet
    component: darknet-gpu
  name: darknet-gpu
spec:
  strategy:
    dockerStrategy:
      dockerfilePath: darknet-gpu.Dockerfile
    type: Docker
  source:
    contextDir: ml/builds
    git:
      uri: https://github.com/stefan-bergstein/computer-vision-streaming-playground.git
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: darknet-gpu:latest
  runPolicy: Serial
  triggers:
  - type: ConfigChange
  successfulBuildsHistoryLimit: 3
  postCommit: {}
  resources: {}