apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: darknet-gpu-volume
  labels:
    component: darknet-gpu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
