apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: cv-streaming
    component: kafka-cv
  name: kafka-cv
spec:
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  source:
    contextDir: kafka-cv
    git:
      uri: https://github.com/stefan-bergstein/computer-vision-streaming-playground.git
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: kafka-cv:cpu
  runPolicy: Serial
  triggers:
  - type: ConfigChange
  successfulBuildsHistoryLimit: 3
  postCommit: {}
  resources: {}