apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-sim-1
  labels:
    app: cam-sim
spec:
  selector:
    matchLabels:
      app: cam-sim
  replicas: 1
  template:
    metadata:
      labels:
        app: cam-sim
    spec:
      containers:
      - name: cam-sim
        image: cam-sim:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kafka-cv-conf-1
        volumeMounts:
          - mountPath: /mnt/kafka-ca-cert
            name: kafka-ca-cert-volume
      volumes:
        - configMap:
            defaultMode: 420
            name: kafka-ca-cert
          name: kafka-ca-cert-volume
